[system]
description = "You are a helpful assistant that provides guidance on how to analyze the fit between a job posting and a candidate's profile."

[[messages]]
type = "human"
text = """Here is the job posting:
<job_posting>{job_posting}</job_posting>

Here is the comprehensive description of the candidate, including their CV, resume, skills, requirements, and desired/undesired job aspects:  
<candidate_description>{candidate_description}</candidate_description>

Your task is to analyze the job fit by comparing the job posting against the candidate description. Assess the following:

1) How well does the candidate's qualifications (education, skills, experience) align with the job requirements and responsibilities? Identify key strengths and potential gaps.

2) How well does the job align with the candidate's ideal job criteria, in terms of both their stated requirements and their listed desired and undesired job aspects? Highlight areas of strong alignment and possible mismatches.

3) Provide an overall assessment of the candidate's fit for this role, considering both their ability to perform the job based on their qualifications, and the fit between the job and the candidate's preferences. 

Consider all the above areas of analysis when writing your report on the job fit between this candidate and this job posting.

Structure your report using the following format, including the XML tags:

<job_fit_report>
  <qualifications_alignment> 
    Assess how well the candidate's qualifications match the job requirements here. Highlight a few key strengths and gaps, with specific examples from the job post and candidate description.
  </qualifications_alignment>

  <job_preferences_alignment>
    Evaluate the fit between the job and the candidate's stated job preferences and requirements. Identify areas where the job strongly aligns with their ideal criteria, and any potential mismatches, referencing specifics from the job post and candidate profile.  
  </job_preferences_alignment>

  <overall_fit_assessment>
    Provide your overall assessment of the candidate's fit for this job here, weighing both their ability to perform the job duties given their qualifications, and the alignment between the job and their preferences. Offer a balanced perspective, noting both positives and potential drawbacks.
  </overall_fit_assessment>
</job_fit_report>"""

[[messages]]
type = "human"
text = """
Identify overlapping skills and experiences between the job posting and the candidate's profile. Highlight key qualifications that match the job requirements and responsibilities.

This will be used to create a cover letter or summary of qualifications for the candidate to submit with their application.

Structure your report using the following format, including the XML tags:

<overlapping_skills>
  <skills>
    List the skills that are common between the job posting and the candidate's profile. Provide specific examples from both the job post and candidate description.
  </skills>

  <experiences>
    Identify relevant experiences that align with the job requirements. Discuss how these experiences make the candidate a strong fit for the role.
  </experiences>
</overlapping_skills>
"""

[[messages]]
type = "human"
text = """
Create 3 cover letters or summaries of qualifications for the candidate based on the overlapping skills and experiences you identified. Craft a compelling narrative that highlights the candidate's strengths and alignment with the job requirements.

Structure your report using the following format, including the XML tags:
<cover_letters>
  <cover_letter>
    Write the cover letter or summary of qualifications here. Tailor the content to emphasize the candidate's relevant skills and experiences that align with the job posting.
  </cover_letter>
</cover_letters>
"""
[[messages]]
type = "human"
text = """
If you were hiring for this role, which cover letter would you find most compelling and why? Provide feedback on the strengths and weaknesses of each cover letter, focusing on the clarity of communication, relevance to the job posting, and overall persuasiveness.

Structure your feedback using the following format, including the XML tags:
<cover_letter_feedback>
  <preferred_cover_letter>
    Provide feedback on the cover letter you find most compelling. Highlight its strengths and areas for improvement, focusing on clarity, relevance, and persuasiveness.
  </preferred_cover_letter>

  <improved_cover_letter>
    Rewrite the <preferred_cover_letter> with any suggestions for improvement based on your feedback. Ensure the revised cover letter addresses the weaknesses you identified.
  </improved_cover_letter>

  <other_cover_letters>
    Provide feedback on the other cover letters, noting their strengths and weaknesses compared to the preferred cover letter. Offer suggestions for improvement.
  </other_cover_letters>
</cover_letter_feedback>
"""
