[system]
description = "You are a helpful assistant that provides guidance on how to analyze the fit between a job posting and a candidate's profile."

[[messages]]
type = "human"
text = """Here is the job posting:
<job_posting>{job_posting}</job_posting>

Here is the comprehensive description of the candidate, including their CV, resume, skills, requirements, and desired/undesired job aspects:  
<candidate_description>{candidate_description}</candidate_description>

Your task is to analyze the job fit by comparing the job posting against the candidate description. Assess the following:

1) How well does the candidate's qualifications (education, skills, experience) align with the job requirements and responsibilities? Identify key strengths and potential gaps.

2) How well does the job align with the candidate's ideal job criteria, in terms of both their stated requirements and their listed desired and undesired job aspects? Highlight areas of strong alignment and possible mismatches.

3) Provide an overall assessment of the candidate's fit for this role, considering both their ability to perform the job based on their qualifications, and the fit between the job and the candidate's preferences. 

Consider all the above areas of analysis when writing your report on the job fit between this candidate and this job posting.

Structure your report using the following format, including the XML tags:

<job_fit_report>
  <qualifications_alignment> 
    Assess how well the candidate's qualifications match the job requirements here. Highlight a few key strengths and gaps, with specific examples from the job post and candidate description.
  </qualifications_alignment>

  <job_preferences_alignment>
    Evaluate the fit between the job and the candidate's stated job preferences and requirements. Identify areas where the job strongly aligns with their ideal criteria, and any potential mismatches, referencing specifics from the job post and candidate profile.  
  </job_preferences_alignment>

  <overall_fit_assessment>
    Provide your overall assessment of the candidate's fit for this job here, weighing both their ability to perform the job duties given their qualifications, and the alignment between the job and their preferences. Offer a balanced perspective, noting both positives and potential drawbacks.
  </overall_fit_assessment>
</job_fit_report>"""

[[messages]]
type = "human"
text = """
Identify overlapping skills and experiences between the job posting and the candidate's profile. Highlight key qualifications that match the job requirements and responsibilities.

This will be used to create a cover letter or summary of qualifications for the candidate to submit with their application.

Structure your report using the following format, including the XML tags:

<overlapping_skills>
  <skills>
    List the skills that are common between the job posting and the candidate's profile. Provide specific examples from both the job post and candidate description.
  </skills>

  <experiences>
    Identify relevant experiences that align with the job requirements. Discuss how these experiences make the candidate a strong fit for the role.
  </experiences>
</overlapping_skills>
"""

[[messages]]
type = "human"
text = """
Your goal is to write a compelling, personalized cover letter from the candidate's perspective that highlights their most relevant skills, experience, and qualifications based on the job description. Pay particular attention to the overlapping_skills_and_experiences that have been identified.

The cover letter should be concise, ideally between 250-400 words. It should demonstrate the candidate's fit and enthusiasm for the role.

Some key points:
- Open the letter by expressing enthusiasm for the job opportunity and company
- Highlight 2-3 of the candidate's most relevant and impressive skills, experience, and accomplishments that directly relate to the job requirements. Be as specific as possible.
- Mention the candidate's interest in the company's mission, products, culture or other relevant factors
- Close the letter by reiterating interest in the role and desire to contribute

Do not use generic, cliched language. Every statement should be highly specific to this candidate and role.

First, take a moment to review the job description, candidate background, and identified overlaps. Jot down your key thoughts and a rough outline for the cover letter in <scratchpad> tags before proceeding.

When you are ready, write the full cover letter inside <cover_letter> tags.
"""
