#!/usr/bin/env zsh

# If no arguments are passed, use the current model
if [ $# -eq 0 ]; then
  _current="email_contractor"
else
  _current=$1
  shift
fi

poetry run python llm_prompt_recurse.py $_current "$@"
